import { useEffect, useState } from 'react';
import { useNavigate } from '@/lib/router-compat';
import { Activity, ArrowRight, CheckCircle2, Network, RefreshCw, ShieldAlert } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { apiClient } from '@/api/client';
import { DEMO_ALERTS, DEMO_FEATURE_CONTRIBUTIONS, DEMO_FORECAST, DEMO_GRAPH_EDGES, DEMO_GRAPH_NODES } from '@/data/mockData';

const forecastData = Array.from({ length: 12 }, (_, index) => ({
  time: `${String(8 + index).padStart(2, '0')}:00`,
  normal: Math.max(28, 82 - index * 3),
  suspicious: 8 + index * 2,
  malicious: 3 + index * 3,
  predicted: index > 6 ? 12 + (index - 6) * 8 : null,
}));

const nodePositions: Record<string, [number, number]> = {
  n1: [126, 150], n2: [330, 72], n3: [350, 220], n4: [82, 270],
  n5: [480, 155], n6: [520, 58], n7: [510, 270], n8: [285, 310],
};

function SectionHeading({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail?: string; action?: React.ReactNode }) {
  return <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#1765F5]">{eyebrow}</p><h2 className="mt-1 text-base font-semibold text-[#10182B]">{title}</h2>{detail && <p className="mt-1 text-xs text-[#506783]">{detail}</p>}</div>{action}</div>;
}

function Metric({ label, value, detail, icon, tone = 'blue' }: { label: string; value: string; detail: string; icon: React.ReactNode; tone?: 'blue' | 'green' | 'red' }) {
  const colors = { blue: 'bg-blue-50 text-[#1765F5]', green: 'bg-emerald-50 text-emerald-600', red: 'bg-red-50 text-red-600' };
  return <div className="group rounded-xl border border-[#DCE5F0] bg-white p-4 shadow-[0_4px_18px_rgba(25,64,104,0.05)] transition duration-200 hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-[0_8px_24px_rgba(25,64,104,0.09)]"><div className="flex items-center justify-between"><span className="text-xs font-medium text-[#506783]">{label}</span><span className={`flex size-8 items-center justify-center rounded-lg ${colors[tone]}`}>{icon}</span></div><p className="mt-4 text-2xl font-semibold tracking-tight text-[#10182B]">{value}</p><p className="mt-1 text-[11px] text-[#506783]">{detail}</p></div>;
}

function NetworkMap({ onSelect }: { onSelect: (id: string) => void }) {
  const selected = DEMO_GRAPH_NODES.find((node) => node.id === 'n1');
  return <div className="relative mt-5 overflow-hidden rounded-lg border border-[#DCE5F0] bg-[#F5F8FC]"><svg viewBox="0 0 600 360" className="h-[300px] w-full md:h-[360px]" role="img" aria-label="Interactive network state map"><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M 24 0 L 0 0 0 24" fill="none" stroke="#DCE5F0" strokeWidth="1" /></pattern></defs><rect width="600" height="360" fill="url(#grid)" />{DEMO_GRAPH_EDGES.map((edge) => { const [x1, y1] = nodePositions[edge.source]; const [x2, y2] = nodePositions[edge.target]; return <g key={edge.id}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={edge.riskScore > 0.6 ? '#F59E0B' : '#A8C5E3'} strokeWidth={edge.riskScore > 0.6 ? 2 : 1.2} strokeDasharray={edge.riskScore > 0.6 ? '6 5' : undefined} opacity=".9"><animate attributeName="stroke-dashoffset" from="22" to="0" dur="1.8s" repeatCount="indefinite" /></line><circle r="3" fill="#1765F5"><animateMotion dur="3s" repeatCount="indefinite" path={`M ${x1} ${y1} L ${x2} ${y2}`} /></circle></g>; })}{DEMO_GRAPH_NODES.map((node) => { const [cx, cy] = nodePositions[node.id]; const danger = node.riskScore >= 0.7; return <g key={node.id} className="cursor-pointer" onClick={() => onSelect(node.id)}><circle cx={cx} cy={cy} r={danger ? 18 : 14} fill={danger ? '#FEE2E2' : '#DCEBFF'} stroke={danger ? '#EF4444' : '#1765F5'} strokeWidth="2"><animate attributeName="r" values={`${danger ? 18 : 14};${danger ? 21 : 16};${danger ? 18 : 14}`} dur="2.6s" repeatCount="indefinite" /></circle><circle cx={cx} cy={cy} r="4" fill={danger ? '#EF4444' : '#1765F5'} /><text x={cx} y={cy + 34} textAnchor="middle" fill="#506783" fontSize="10">{node.label.split(' ')[0]}</text></g>; })}</svg><div className="absolute left-4 top-4 rounded-md border border-[#DCE5F0] bg-white/95 px-3 py-2 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-wider text-[#506783]">Current network state</p><p className="mt-1 text-sm font-semibold text-[#10182B]">Elevated lateral movement</p><p className="mt-1 text-[10px] text-amber-700">Predicted path highlighted</p></div>{selected && <div className="absolute bottom-4 right-4 rounded-md border border-[#DCE5F0] bg-white/95 px-3 py-2 shadow-sm"><p className="text-[10px] uppercase tracking-wider text-[#506783]">Selected node</p><p className="mt-1 text-sm font-semibold text-[#10182B]">{selected.label}</p><p className="text-[10px] text-red-600">Risk {Math.round(selected.riskScore * 100)}% · {selected.connections} connections</p></div>}</div>;
}

export function RealDashboard() {
  const navigate = useNavigate();
  const [apiState, setApiState] = useState<'live' | 'fallback' | 'checking'>('checking');
  const [apiMessage, setApiMessage] = useState('Connecting to analytics service...');
  const [selectedNode, setSelectedNode] = useState('n1');
  const [refreshing, setRefreshing] = useState(false);

  const checkApi = async () => { setRefreshing(true); setApiState('checking'); try { await apiClient.get('/api/health'); setApiState('live'); setApiMessage('Supabase database and API connected'); } catch (error) { setApiState('fallback'); setApiMessage(error instanceof Error ? `${error.message} Showing demo intelligence.` : 'Supabase API unavailable. Showing demo intelligence.'); } finally { setRefreshing(false); } };
  useEffect(() => { void checkApi(); }, []);

  return <main className="min-h-full bg-[var(--background)] px-4 py-6 text-[var(--foreground)] md:px-7 lg:px-8"><div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#1765F5]">FORTEXA · Command Center</p><h1 className="mt-2 text-2xl font-semibold tracking-tight md:text-3xl">Forecast the threat before impact.</h1><p className="mt-2 max-w-2xl text-sm text-[#506783]">Network data flows into a learned world model, future-state simulation, and actionable attack forecast.</p></div><button onClick={() => void checkApi()} disabled={refreshing} className="inline-flex items-center gap-2 rounded-md bg-[#1765F5] px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-[#0D56E8] focus:outline-none focus:ring-2 focus:ring-blue-300 disabled:opacity-60"><RefreshCw className={`size-4 ${refreshing ? 'animate-spin' : ''}`} /> Refresh intelligence</button></header>
    <div className={`flex flex-wrap items-center justify-between gap-3 rounded-lg border px-4 py-3 ${apiState === 'live' ? 'border-emerald-200 bg-emerald-50' : apiState === 'fallback' ? 'border-amber-200 bg-amber-50' : 'border-blue-200 bg-blue-50'}`}><div className="flex items-center gap-2 text-xs"><span className={`size-2 rounded-full ${apiState === 'live' ? 'bg-emerald-500' : apiState === 'fallback' ? 'bg-amber-500' : 'animate-pulse bg-blue-500'}`} /><span className="font-semibold">{apiState === 'live' ? 'LIVE ANALYTICS' : apiState === 'fallback' ? 'DEMO INTELLIGENCE' : 'CONNECTING'}</span><span className="text-[#506783]">{apiMessage}</span></div><span className="text-[10px] font-medium uppercase tracking-wider text-[#506783]">Model FORTEXA v2.1.4</span></div>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Network Health" value="98.4%" detail="Within operational baseline" icon={<CheckCircle2 className="size-4" />} tone="green" /><Metric label="Active Devices" value="142" detail="8 suspicious entities" icon={<Network className="size-4" />} /><Metric label="Active Flows" value="1.2M" detail="+8.2% in the last hour" icon={<Activity className="size-4" />} /><Metric label="Threat Probability" value="72%" detail="High · next 12 minutes" icon={<ShieldAlert className="size-4" />} tone="red" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-[#DCE5F0] bg-white p-5 shadow-[0_4px_18px_rgba(25,64,104,0.05)]"><SectionHeading eyebrow="Live network state" title="Entity relationship map" detail="Traffic flow, suspicious nodes, and the predicted attack path" action={<button onClick={() => navigate('/graph')} className="text-xs font-medium text-[#1765F5] hover:text-[#0D56E8]">Open graph <ArrowRight className="ml-1 inline size-3" /></button>} /><NetworkMap onSelect={setSelectedNode} /><p className="mt-2 text-[10px] text-[#506783]">Selected entity: {DEMO_GRAPH_NODES.find((node) => node.id === selectedNode)?.label ?? '10.0.1.42'} · Click any node for details</p></div><div className="rounded-xl border border-[#DCE5F0] bg-white p-5 shadow-[0_4px_18px_rgba(25,64,104,0.05)]"><SectionHeading eyebrow="Risk panel" title="Attack forecast" detail="Model-estimated progression from the current state" /><div className="mt-6 flex items-center gap-6"><div className="relative flex size-36 shrink-0 items-center justify-center rounded-full border-[12px] border-red-100"><div className="absolute inset-0 rounded-full border-[12px] border-transparent border-l-red-500 border-t-red-500" /><div className="text-center"><p className="text-3xl font-semibold">72%</p><p className="text-[10px] font-semibold uppercase tracking-wider text-red-600">High risk</p></div></div><div><p className="text-sm font-semibold">Likely progression within 12 minutes</p><p className="mt-2 text-xs leading-5 text-[#506783]">Reconnaissance detected. The world model projects lateral movement toward privileged systems.</p></div></div><div className="mt-6 space-y-2">{['Reconnaissance', 'Lateral Movement', 'Privilege Escalation', 'Data Exfiltration'].map((stage, index) => <div key={stage} className="flex items-center gap-3 text-xs"><span className={`flex size-6 items-center justify-center rounded-full text-[10px] font-semibold ${index === 0 ? 'bg-blue-100 text-[#1765F5]' : 'bg-slate-100 text-[#506783]'}`}>{index + 1}</span><span className="text-[#506783]">{stage}</span>{index < 3 && <ArrowRight className="ml-auto size-3 text-[#B2C3D6]" />}</div>)}</div><button onClick={() => navigate('/forecast')} className="mt-6 w-full rounded-md border border-[#1765F5] bg-white px-3 py-2 text-xs font-semibold text-[#1765F5] transition hover:bg-[#DCEBFF]">Review forecast</button></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-[#DCE5F0] bg-white p-5 shadow-[0_4px_18px_rgba(25,64,104,0.05)]"><SectionHeading eyebrow="Observed → predicted" title="Threat probability over next 24 hours" detail="Historical traffic and forecast trajectory" /><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={forecastData}><defs><linearGradient id="riskFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1765F5" stopOpacity=".22" /><stop offset="100%" stopColor="#1765F5" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#E8EEF5" strokeDasharray="3 3" /><XAxis dataKey="time" tick={{ fontSize: 10, fill: '#506783' }} /><YAxis tick={{ fontSize: 10, fill: '#506783' }} unit="%" /><Tooltip /><Area type="monotone" dataKey="normal" stroke="#1765F5" fill="url(#riskFill)" strokeWidth={2} name="Normal" /><Area type="monotone" dataKey="suspicious" stroke="#F59E0B" fill="none" strokeWidth={2} name="Suspicious" /><Area type="monotone" dataKey="malicious" stroke="#EF4444" fill="none" strokeWidth={2} name="Malicious" /><Area type="monotone" dataKey="predicted" stroke="#1765F5" fill="none" strokeDasharray="5 4" strokeWidth={2} name="Predicted" /></AreaChart></ResponsiveContainer></div><div className="mt-2 flex gap-4 text-[10px] text-[#506783]"><span><i className="mr-1 inline-block size-2 rounded-full bg-[#1765F5]" />Observed</span><span><i className="mr-1 inline-block size-2 rounded-full bg-[#F59E0B]" />Suspicious</span><span><i className="mr-1 inline-block size-2 rounded-full bg-[#EF4444]" />Malicious</span></div></div><div className="rounded-xl border border-[#DCE5F0] bg-white p-5 shadow-[0_4px_18px_rgba(25,64,104,0.05)]"><SectionHeading eyebrow="MITRE ATT&CK mapping" title="Predicted techniques" detail="Mapped from current state dynamics" /><div className="mt-5 space-y-3">{DEMO_FORECAST.predictedAttackProgression.slice(0, 5).map((stage) => <div key={stage.id} className="flex items-center justify-between border-b border-[#EEF2F7] pb-3 last:border-0"><div><p className="text-xs font-medium text-[#10182B]">{stage.techniqueName}</p><p className="mt-0.5 text-[10px] text-[#506783]">{stage.mitreId} · {stage.tacticName}</p></div><span className={`text-xs font-semibold ${stage.probability > .7 ? 'text-red-600' : stage.probability > .5 ? 'text-amber-600' : 'text-[#1765F5]'}`}>{Math.round(stage.probability * 100)}%</span></div>)}</div><button onClick={() => navigate('/attack-timeline')} className="mt-4 text-xs font-semibold text-[#1765F5]">View ATT&CK detail <ArrowRight className="ml-1 inline size-3" /></button></div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-[#DCE5F0] bg-white p-5 shadow-[0_4px_18px_rgba(25,64,104,0.05)]"><SectionHeading eyebrow="Attack progression" title="Current state → future state simulation" /><div className="mt-5 grid gap-3 sm:grid-cols-4">{['Current State', 'Predicted +1', 'Predicted +2', 'Predicted +3'].map((state, index) => <div key={state} className="relative rounded-lg border border-[#DCE5F0] bg-[#F5F8FC] p-3"><span className="text-[10px] font-semibold uppercase tracking-wider text-[#1765F5]">S(t{index ? `+${index}` : ''})</span><p className="mt-3 text-xs font-semibold">{['Elevated scanning', 'Lateral movement', 'Privilege access', 'Data staging'][index]}</p><p className="mt-1 text-[10px] text-[#506783]">Risk {['72%', '79%', '84%', '91%'][index]}</p>{index < 3 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden size-4 bg-white text-[#9CB5CF] sm:block" />}</div>)}</div></div><div className="rounded-xl border border-[#DCE5F0] bg-white p-5 shadow-[0_4px_18px_rgba(25,64,104,0.05)]"><SectionHeading eyebrow="Explainability" title="Why did FORTEXA predict this threat?" action={<button onClick={() => navigate('/explainability')} className="text-xs font-medium text-[#1765F5]">Details</button>} /><div className="mt-4 space-y-3">{DEMO_FEATURE_CONTRIBUTIONS.slice(0, 5).map((feature) => <div key={feature.feature}><div className="mb-1 flex justify-between text-xs"><span>{feature.feature}</span><span className="font-mono text-red-600">+{feature.contribution.toFixed(2)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#EEF2F7]"><div className="h-full rounded-full bg-[#1765F5]" style={{ width: `${Math.min(100, feature.contribution * 360)}%` }} /></div></div>)}</div></div></section>
    <section className="rounded-xl border border-[#DCE5F0] bg-white p-5 shadow-[0_4px_18px_rgba(25,64,104,0.05)]"><SectionHeading eyebrow="Recent threats" title="Network activity requiring attention" action={<button onClick={() => navigate('/alerts')} className="text-xs font-medium text-[#1765F5]">View all alerts <ArrowRight className="ml-1 inline size-3" /></button>} /><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b border-[#DCE5F0] text-[10px] uppercase tracking-wider text-[#506783]"><tr><th className="pb-3 font-semibold">Timestamp</th><th className="pb-3 font-semibold">Source</th><th className="pb-3 font-semibold">Destination</th><th className="pb-3 font-semibold">Threat type</th><th className="pb-3 font-semibold">Confidence</th><th className="pb-3 font-semibold">Status</th></tr></thead><tbody>{DEMO_ALERTS.slice(0, 4).map((alert, index) => <tr key={alert.id} className="border-b border-[#EEF2F7] transition hover:bg-[#F5F8FC]"><td className="py-3 text-[#506783]">09:{42 - index * 4}</td><td className="py-3 font-mono text-[#10182B]">{alert.affectedEntities[0]}</td><td className="py-3 font-mono text-[#506783]">{alert.affectedEntities[1] ?? 'Internal'}</td><td className="py-3"><span className="inline-flex items-center gap-1.5"><span className={`size-1.5 rounded-full ${alert.severity === 'critical' ? 'bg-red-500' : alert.severity === 'high' ? 'bg-amber-500' : 'bg-blue-500'}`} />{alert.predictedBehavior}</span></td><td className="py-3 font-medium">{Math.round(alert.confidence * 100)}%</td><td className="py-3"><span className={`rounded px-2 py-1 text-[10px] font-semibold uppercase ${alert.isAcknowledged ? 'bg-slate-100 text-[#506783]' : 'bg-red-50 text-red-600'}`}>{alert.isAcknowledged ? 'Reviewed' : 'Action needed'}</span></td></tr>)}</tbody></table></div></section>
  </div></main>;
}
