/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAttackTimelineRouteImport } from './routes/_app/attack-timeline'
import { Route as AppCopilotRouteImport } from './routes/_app/copilot'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDatasetsRouteImport } from './routes/_app/datasets'
import { Route as AppEvaluationRouteImport } from './routes/_app/evaluation'
import { Route as AppExplainabilityRouteImport } from './routes/_app/explainability'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppGraphRouteImport } from './routes/_app/graph'
import { Route as AppIngestionRouteImport } from './routes/_app/ingestion'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppNetworkSecurityRouteImport } from './routes/_app/network-security'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppResearchRouteImport } from './routes/_app/research'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSocRouteImport } from './routes/_app/soc'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as AppWorldModelRouteImport } from './routes/_app/world-model'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiDatasetsRouteImport } from './routes/api/datasets'
import { Route as ApiDemoRouteImport } from './routes/api/demo'
import { Route as ApiGraphRouteImport } from './routes/api/graph'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiNetworkFlowsRouteImport } from './routes/api/network.flows'
import { Route as ApiNetworkStatesRouteImport } from './routes/api/network.states'
import { Route as ApiUploadsIdRouteImport } from './routes/api/uploads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackTimelineRoute = AppAttackTimelineRouteImport.update({
  id: '/attack-timeline',
  path: '/attack-timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsRoute = AppDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationRoute = AppEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AppRoute,
} as any)
const AppExplainabilityRoute = AppExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestionRoute = AppIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkSecurityRoute = AppNetworkSecurityRouteImport.update({
  id: '/network-security',
  path: '/network-security',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSocRoute = AppSocRouteImport.update({
  id: '/soc',
  path: '/soc',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldModelRoute = AppWorldModelRouteImport.update({
  id: '/world-model',
  path: '/world-model',
  getParentRoute: () => AppRoute,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasetsRoute = ApiDatasetsRouteImport.update({
  id: '/api/datasets',
  path: '/api/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphRoute = ApiGraphRouteImport.update({
  id: '/api/graph',
  path: '/api/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkFlowsRoute = ApiNetworkFlowsRouteImport.update({
  id: '/api/network/flows',
  path: '/api/network/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkStatesRoute = ApiNetworkStatesRouteImport.update({
  id: '/api/network/states',
  path: '/api/network/states',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUploadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/attack-timeline': typeof AppAttackTimelineRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/datasets': typeof AppDatasetsRoute
  '/evaluation': typeof AppEvaluationRoute
  '/explainability': typeof AppExplainabilityRoute
  '/forecast': typeof AppForecastRoute
  '/graph': typeof AppGraphRoute
  '/ingestion': typeof AppIngestionRoute
  '/network': typeof AppNetworkRoute
  '/network-security': typeof AppNetworkSecurityRoute
  '/reports': typeof AppReportsRoute
  '/research': typeof AppResearchRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/soc': typeof AppSocRoute
  '/workspace': typeof AppWorkspaceRoute
  '/world-model': typeof AppWorldModelRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/datasets': typeof ApiDatasetsRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/network/flows': typeof ApiNetworkFlowsRoute
  '/api/network/states': typeof ApiNetworkStatesRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/attack-timeline': typeof AppAttackTimelineRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/datasets': typeof AppDatasetsRoute
  '/evaluation': typeof AppEvaluationRoute
  '/explainability': typeof AppExplainabilityRoute
  '/forecast': typeof AppForecastRoute
  '/graph': typeof AppGraphRoute
  '/ingestion': typeof AppIngestionRoute
  '/network': typeof AppNetworkRoute
  '/network-security': typeof AppNetworkSecurityRoute
  '/reports': typeof AppReportsRoute
  '/research': typeof AppResearchRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/soc': typeof AppSocRoute
  '/workspace': typeof AppWorkspaceRoute
  '/world-model': typeof AppWorldModelRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/datasets': typeof ApiDatasetsRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/network/flows': typeof ApiNetworkFlowsRoute
  '/api/network/states': typeof ApiNetworkStatesRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/attack-timeline': typeof AppAttackTimelineRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/datasets': typeof AppDatasetsRoute
  '/_app/evaluation': typeof AppEvaluationRoute
  '/_app/explainability': typeof AppExplainabilityRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/graph': typeof AppGraphRoute
  '/_app/ingestion': typeof AppIngestionRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/network-security': typeof AppNetworkSecurityRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/research': typeof AppResearchRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/soc': typeof AppSocRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/_app/world-model': typeof AppWorldModelRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/datasets': typeof ApiDatasetsRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/network/flows': typeof ApiNetworkFlowsRoute
  '/api/network/states': typeof ApiNetworkStatesRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/alerts'
    | '/attack-timeline'
    | '/copilot'
    | '/dashboard'
    | '/datasets'
    | '/evaluation'
    | '/explainability'
    | '/forecast'
    | '/graph'
    | '/ingestion'
    | '/network'
    | '/network-security'
    | '/reports'
    | '/research'
    | '/security'
    | '/settings'
    | '/soc'
    | '/workspace'
    | '/world-model'
    | '/api/admin'
    | '/api/alerts'
    | '/api/datasets'
    | '/api/demo'
    | '/api/graph'
    | '/api/health'
    | '/api/uploads'
    | '/api/network/flows'
    | '/api/network/states'
    | '/api/uploads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/alerts'
    | '/attack-timeline'
    | '/copilot'
    | '/dashboard'
    | '/datasets'
    | '/evaluation'
    | '/explainability'
    | '/forecast'
    | '/graph'
    | '/ingestion'
    | '/network'
    | '/network-security'
    | '/reports'
    | '/research'
    | '/security'
    | '/settings'
    | '/soc'
    | '/workspace'
    | '/world-model'
    | '/api/admin'
    | '/api/alerts'
    | '/api/datasets'
    | '/api/demo'
    | '/api/graph'
    | '/api/health'
    | '/api/uploads'
    | '/api/network/flows'
    | '/api/network/states'
    | '/api/uploads/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/alerts'
    | '/_app/attack-timeline'
    | '/_app/copilot'
    | '/_app/dashboard'
    | '/_app/datasets'
    | '/_app/evaluation'
    | '/_app/explainability'
    | '/_app/forecast'
    | '/_app/graph'
    | '/_app/ingestion'
    | '/_app/network'
    | '/_app/network-security'
    | '/_app/reports'
    | '/_app/research'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/soc'
    | '/_app/workspace'
    | '/_app/world-model'
    | '/api/admin'
    | '/api/alerts'
    | '/api/datasets'
    | '/api/demo'
    | '/api/graph'
    | '/api/health'
    | '/api/uploads'
    | '/api/network/flows'
    | '/api/network/states'
    | '/api/uploads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiDatasetsRoute: typeof ApiDatasetsRoute
  ApiDemoRoute: typeof ApiDemoRoute
  ApiGraphRoute: typeof ApiGraphRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiNetworkFlowsRoute: typeof ApiNetworkFlowsRoute
  ApiNetworkStatesRoute: typeof ApiNetworkStatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-timeline': {
      id: '/_app/attack-timeline'
      path: '/attack-timeline'
      fullPath: '/attack-timeline'
      preLoaderRoute: typeof AppAttackTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datasets': {
      id: '/_app/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AppDatasetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluation': {
      id: '/_app/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof AppEvaluationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explainability': {
      id: '/_app/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof AppExplainabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph': {
      id: '/_app/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingestion': {
      id: '/_app/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof AppIngestionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network-security': {
      id: '/_app/network-security'
      path: '/network-security'
      fullPath: '/network-security'
      preLoaderRoute: typeof AppNetworkSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/soc': {
      id: '/_app/soc'
      path: '/soc'
      fullPath: '/soc'
      preLoaderRoute: typeof AppSocRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/world-model': {
      id: '/_app/world-model'
      path: '/world-model'
      fullPath: '/world-model'
      preLoaderRoute: typeof AppWorldModelRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasets': {
      id: '/api/datasets'
      path: '/api/datasets'
      fullPath: '/api/datasets'
      preLoaderRoute: typeof ApiDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph': {
      id: '/api/graph'
      path: '/api/graph'
      fullPath: '/api/graph'
      preLoaderRoute: typeof ApiGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network/flows': {
      id: '/api/network/flows'
      path: '/api/network/flows'
      fullPath: '/api/network/flows'
      preLoaderRoute: typeof ApiNetworkFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network/states': {
      id: '/api/network/states'
      path: '/api/network/states'
      fullPath: '/api/network/states'
      preLoaderRoute: typeof ApiNetworkStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAttackTimelineRoute: typeof AppAttackTimelineRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatasetsRoute: typeof AppDatasetsRoute
  AppEvaluationRoute: typeof AppEvaluationRoute
  AppExplainabilityRoute: typeof AppExplainabilityRoute
  AppForecastRoute: typeof AppForecastRoute
  AppGraphRoute: typeof AppGraphRoute
  AppIngestionRoute: typeof AppIngestionRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppNetworkSecurityRoute: typeof AppNetworkSecurityRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocRoute: typeof AppSocRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppWorldModelRoute: typeof AppWorldModelRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAttackTimelineRoute: AppAttackTimelineRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatasetsRoute: AppDatasetsRoute,
  AppEvaluationRoute: AppEvaluationRoute,
  AppExplainabilityRoute: AppExplainabilityRoute,
  AppForecastRoute: AppForecastRoute,
  AppGraphRoute: AppGraphRoute,
  AppIngestionRoute: AppIngestionRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppNetworkSecurityRoute: AppNetworkSecurityRoute,
  AppReportsRoute: AppReportsRoute,
  AppResearchRoute: AppResearchRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocRoute: AppSocRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppWorldModelRoute: AppWorldModelRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiUploadsRouteChildren {
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsIdRoute: ApiUploadsIdRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiDatasetsRoute: ApiDatasetsRoute,
  ApiDemoRoute: ApiDemoRoute,
  ApiGraphRoute: ApiGraphRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiNetworkFlowsRoute: ApiNetworkFlowsRoute,
  ApiNetworkStatesRoute: ApiNetworkStatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
